// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_name", Type: field.TypeString, Size: 50},
		{Name: "last_name", Type: field.TypeString, Size: 50},
		{Name: "email", Type: field.TypeString, Size: 500},
		{Name: "phone", Type: field.TypeString, Size: 30},
		{Name: "category", Type: field.TypeInt},
		{Name: "message", Type: field.TypeString, Size: 5000},
		{Name: "verify_code", Type: field.TypeString, Size: 10},
		{Name: "is_verified", Type: field.TypeBool, Default: false},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContactsTable,
	}
)

func init() {
}
