// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"pentag.kr/api-server/ent/contact"
)

// ContactCreate is the builder for creating a Contact entity.
type ContactCreate struct {
	config
	mutation *ContactMutation
	hooks    []Hook
}

// SetFirstName sets the "first_name" field.
func (cc *ContactCreate) SetFirstName(s string) *ContactCreate {
	cc.mutation.SetFirstName(s)
	return cc
}

// SetLastName sets the "last_name" field.
func (cc *ContactCreate) SetLastName(s string) *ContactCreate {
	cc.mutation.SetLastName(s)
	return cc
}

// SetEmail sets the "email" field.
func (cc *ContactCreate) SetEmail(s string) *ContactCreate {
	cc.mutation.SetEmail(s)
	return cc
}

// SetPhone sets the "phone" field.
func (cc *ContactCreate) SetPhone(s string) *ContactCreate {
	cc.mutation.SetPhone(s)
	return cc
}

// SetCategory sets the "category" field.
func (cc *ContactCreate) SetCategory(i int) *ContactCreate {
	cc.mutation.SetCategory(i)
	return cc
}

// SetMessage sets the "message" field.
func (cc *ContactCreate) SetMessage(s string) *ContactCreate {
	cc.mutation.SetMessage(s)
	return cc
}

// SetVerifyCode sets the "verify_code" field.
func (cc *ContactCreate) SetVerifyCode(s string) *ContactCreate {
	cc.mutation.SetVerifyCode(s)
	return cc
}

// SetIsVerified sets the "is_verified" field.
func (cc *ContactCreate) SetIsVerified(b bool) *ContactCreate {
	cc.mutation.SetIsVerified(b)
	return cc
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (cc *ContactCreate) SetNillableIsVerified(b *bool) *ContactCreate {
	if b != nil {
		cc.SetIsVerified(*b)
	}
	return cc
}

// Mutation returns the ContactMutation object of the builder.
func (cc *ContactCreate) Mutation() *ContactMutation {
	return cc.mutation
}

// Save creates the Contact in the database.
func (cc *ContactCreate) Save(ctx context.Context) (*Contact, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ContactCreate) SaveX(ctx context.Context) *Contact {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ContactCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ContactCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ContactCreate) defaults() {
	if _, ok := cc.mutation.IsVerified(); !ok {
		v := contact.DefaultIsVerified
		cc.mutation.SetIsVerified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ContactCreate) check() error {
	if _, ok := cc.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Contact.first_name"`)}
	}
	if v, ok := cc.mutation.FirstName(); ok {
		if err := contact.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Contact.first_name": %w`, err)}
		}
	}
	if _, ok := cc.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Contact.last_name"`)}
	}
	if v, ok := cc.mutation.LastName(); ok {
		if err := contact.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "Contact.last_name": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Contact.email"`)}
	}
	if v, ok := cc.mutation.Email(); ok {
		if err := contact.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Contact.email": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Contact.phone"`)}
	}
	if v, ok := cc.mutation.Phone(); ok {
		if err := contact.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Contact.phone": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Contact.category"`)}
	}
	if v, ok := cc.mutation.Category(); ok {
		if err := contact.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Contact.category": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "Contact.message"`)}
	}
	if v, ok := cc.mutation.Message(); ok {
		if err := contact.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Contact.message": %w`, err)}
		}
	}
	if _, ok := cc.mutation.VerifyCode(); !ok {
		return &ValidationError{Name: "verify_code", err: errors.New(`ent: missing required field "Contact.verify_code"`)}
	}
	if v, ok := cc.mutation.VerifyCode(); ok {
		if err := contact.VerifyCodeValidator(v); err != nil {
			return &ValidationError{Name: "verify_code", err: fmt.Errorf(`ent: validator failed for field "Contact.verify_code": %w`, err)}
		}
	}
	if _, ok := cc.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "Contact.is_verified"`)}
	}
	return nil
}

func (cc *ContactCreate) sqlSave(ctx context.Context) (*Contact, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ContactCreate) createSpec() (*Contact, *sqlgraph.CreateSpec) {
	var (
		_node = &Contact{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(contact.Table, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.FirstName(); ok {
		_spec.SetField(contact.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := cc.mutation.LastName(); ok {
		_spec.SetField(contact.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := cc.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := cc.mutation.Phone(); ok {
		_spec.SetField(contact.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := cc.mutation.Category(); ok {
		_spec.SetField(contact.FieldCategory, field.TypeInt, value)
		_node.Category = value
	}
	if value, ok := cc.mutation.Message(); ok {
		_spec.SetField(contact.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := cc.mutation.VerifyCode(); ok {
		_spec.SetField(contact.FieldVerifyCode, field.TypeString, value)
		_node.VerifyCode = value
	}
	if value, ok := cc.mutation.IsVerified(); ok {
		_spec.SetField(contact.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	return _node, _spec
}

// ContactCreateBulk is the builder for creating many Contact entities in bulk.
type ContactCreateBulk struct {
	config
	err      error
	builders []*ContactCreate
}

// Save creates the Contact entities in the database.
func (ccb *ContactCreateBulk) Save(ctx context.Context) ([]*Contact, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Contact, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ContactCreateBulk) SaveX(ctx context.Context) []*Contact {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ContactCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ContactCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
